// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace sgosat.Repositorio.Migrations
{
    [DbContext(typeof(sgosatContexto))]
    [Migration("20250403095634_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sgosat.Dominio.Entidades.OrdemServico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAbertura");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataConclusao");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacoes");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacoes1");

                    b.Property<string>("ServicoRealizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusOSID")
                        .HasColumnType("int")
                        .HasColumnName("StatusOSID");

                    b.HasKey("ID");

                    b.ToTable("OrdemServico", (string)null);
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.OrdemServicoPessoas", b =>
                {
                    b.Property<int>("OrdemServicoID")
                        .HasColumnType("int")
                        .HasColumnName("OrdemServicoID");

                    b.Property<int>("PessoaID")
                        .HasColumnType("int")
                        .HasColumnName("PessoaID");

                    b.Property<string>("Funcao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Funcao");

                    b.HasKey("OrdemServicoID", "PessoaID");

                    b.HasIndex("PessoaID");

                    b.ToTable("OrdemServicoPessoas");
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.Pessoa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<bool>("Cliente")
                        .HasColumnType("bit")
                        .HasColumnName("Cliente");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complemento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<bool>("Funcionario")
                        .HasColumnType("bit")
                        .HasColumnName("Funcionario");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numero");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefone");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoPessoa");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UF");

                    b.HasKey("ID");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<int>("PessoaID")
                        .HasColumnType("int")
                        .HasColumnName("PessoaID");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Senha");

                    b.Property<int>("TipoUsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("TipoUsuarioID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("ID");

                    b.HasIndex("PessoaID")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.OrdemServicoPessoas", b =>
                {
                    b.HasOne("sgosat.Dominio.Entidades.OrdemServico", "OrdemServico")
                        .WithMany("OrdemServicoPessoas")
                        .HasForeignKey("OrdemServicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgosat.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithMany("OrdemServicoPessoas")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("sgosat.Dominio.Entidades.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("sgosat.Dominio.Entidades.Usuario", "PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.OrdemServico", b =>
                {
                    b.Navigation("OrdemServicoPessoas");
                });

            modelBuilder.Entity("sgosat.Dominio.Entidades.Pessoa", b =>
                {
                    b.Navigation("OrdemServicoPessoas");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
